version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/simplesurance/jenkins-exporter
